name: Deploy to Minikube using GitHub Actions

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build Node.js Docker Image and deploy to Minikube
    steps:
    - uses: actions/checkout@v2

    - name: Start Minikube
      uses: medyagh/setup-minikube@master

    - name: Verify Kubernetes cluster
      run: kubectl get pods -A

    - name: Build Docker image inside Minikube
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        docker build -f ./Dockerfile -t nodejs-app:latest .
        docker images

    - name: Deploy to Minikube
      run: kubectl apply -f k8s-node-app.yaml

    - name: Wait for pod to be ready
      run: |
        echo "Waiting for pod to be ready..."
        kubectl wait --for=condition=ready pod -l app=nodejs-app --timeout=60s
        kubectl get pods

    - name: Show pod status and logs (on failure)
      if: failure()
      run: |
        echo "Status of pods:"
        kubectl get pods -o wide
        echo "Describing pod:"
        kubectl describe pod -l app=nodejs-app
        echo "Logs of pod:"
        kubectl logs -l app=nodejs-app

    - name: Test service URLs
      if: success()
      run: |
        minikube service list
        minikube service nodejs-app --url
